import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  plugins: [react()],
  server: {
    // The prose seam (rationale + notification copy) is generated by Claude in the
    // Node server (server/index.mjs). The browser calls /api/*; Vite proxies it so
    // the ANTHROPIC_API_KEY never reaches the client.
    proxy: {
      '/api': { target: 'http://localhost:8787', changeOrigin: true },
    },
  },
})
